In [4]:
# Imports
import pandas as pd
import re
import json
import duckdb
import matplotlib.pyplot as plt

## Get ground Truth

In [5]:
ground_truth_napoleon = pd.read_csv('../data/weight_files/ground_truth_raw/GT_napoleon_in_edges_raw.csv')

In [43]:
ground_truth_napoleon = ground_truth_napoleon.drop_duplicates(subset='id', keep='first').reset_index(drop=True)

In [44]:
ground_truth_napoleon = ground_truth_napoleon[["label", "text" ]]

In [45]:
print(ground_truth_napoleon.shape)
ground_truth_napoleon

(46, 2)

,label,text
0,"[{""end"":56226,""text"":""Napoleon"",""start"":56218,...",upload/286914/1fdf5af5-Voltaire_en.txt
1,"[{""end"":929,""text"":""Napoleon"",""start"":921,""lab...",upload/286914/5cc5cfef-Vincent-Marie_Viénot_Co...
2,"[{""end"":38625,""text"":""Napoleon Bonaparte"",""sta...",upload/286914/341b596e-Robert_Clive_en.txt
3,NaN,upload/286914/6b10b085-Prince_Philippe_Count_o...
4,NaN,upload/286914/73f76387-Prince_Josias_of_Saxe-C...
5,"[{""end"":5885,""text"":""Napoleon's"",""start"":5875,...",upload/286914/d9f53915-Prince_Frederick_Duke_o...
6,"[{""end"":9272,""text"":""Napoleon"",""start"":9264,""l...",upload/286914/3d352a8f-Prince_Ferdinand_Philip...
7,"[{""end"":6466,""text"":""Napoleon"",""start"":6458,""l...",upload/286914/f797fa95-Paolo_Virzì_en.txt
8,"[{""end"":868,""text"":""Napoleon Bonaparte's"",""sta...",upload/286914/57a687d9-Oscar_I_of_Sweden_en.txt
9,"[{""end"":627,""text"":""Napoleon"",""start"":619,""lab...",upload/286914/645a6703-Nicolas-Charles_Bochsa_...
10,"[{""end"":3502,""text"":""Napoleon"",""start"":3494,""l...",upload/286914/3844b1cc-Mikhail_Tukhachevsky_en...
11,"[{""end"":5417,""text"":""Napoleon"",""start"":5409,""l...",upload/286914/e7bc14e5-Maurice_dElbée_en.txt
12,"[{""end"":13052,""text"":""Napoleon"",""start"":13044,...",upload/286914/eb309a99-Leo_Tolstoy_en.txt
13,"[{""end"":63269,""text"":""Napoleon Bonaparte"",""sta...",upload/286914/c9546d53-Julius_Caesar_en.txt
14,"[{""end"":399,""text"":""Napoleon Bonaparte"",""start...",upload/286914/63c635bc-Józef_Bem_en.txt
15,"[{""end"":2504,""text"":""Napoleon I"",""start"":2494,...",upload/286914/66553665-Joseph_Škoda_en.txt
16,"[{""end"":25209,""text"":""Napoleon"",""start"":25201,...",upload/286914/adcd9a9f-Joseph_Haydn_en.txt
17,"[{""end"":5050,""text"":""Napoleon"",""start"":5042,""l...",upload/286914/66040578-Joseph_de_Maistre_en.txt
18,"[{""end"":2552,""text"":""Napoleon I"",""start"":2542,...",upload/286914/2a7a0161-Joel_Roberts_Poinsett_e...
19,"[{""end"":4537,""text"":""Napoleon"",""start"":4529,""l...",upload/286914/d70c6ed8-Joan_Elizabeth_Bichier_...
20,"[{""end"":286,""text"":""Napoleon"",""start"":278,""lab...",upload/286914/34c2e4aa-Jean-Antoine_Chaptal_en...
21,"[{""end"":228,""text"":""Napoleon's"",""start"":218,""l...",upload/286914/124940a6-Jean_Maximilien_Lamarqu...
22,"[{""end"":2050,""text"":""Napoleon's"",""start"":2040,...",upload/286914/88288647-Jacques_Laffitte_en.txt
23,"[{""end"":1873,""text"":""Napoleon"",""start"":1865,""l...",upload/286914/4e7f3b1c-Ida_Laura_Pfeiffer_en.txt
24,"[{""end"":368,""text"":""Napoleon"",""start"":360,""lab...",upload/286914/f33b29d3-Germinal_Pierre_Dandeli...
25,"[{""end"":1422,""text"":""Napoleon Bonaparte"",""star...",upload/286914/f31a453d-Georges_Cadoudal_en.txt
26,"[{""end"":13251,""text"":""Napoleon"",""start"":13243,...",upload/286914/1a0518d4-Gaspard_de_Prony_en.txt
27,"[{""end"":2135,""text"":""Napoleon"",""start"":2127,""l...",upload/286914/fcf3d393-Friedrich_Wilhelm_Freih...
28,"[{""end"":112828,""text"":""Napoleon"",""start"":11282...",upload/286914/747aed0b-Frederick_II_Holy_Roman...
29,"[{""end"":4488,""text"":""Napoleon"",""start"":4480,""l...",upload/286914/5173fad9-Frederick_Augustus_I_of...
30,"[{""end"":6951,""text"":""Napoleon Bonaparte"",""star...",upload/286914/a1b960d4-Franz_Joseph_Gall_en.txt
31,"[{""end"":356,""text"":""Napoleon"",""start"":348,""lab...",upload/286914/0efa6af0-François_Christophe_de_...
32,"[{""end"":641,""text"":""Napoleon"",""start"":633,""lab...",upload/286914/3ecee844-Francisco_Martínez_de_l...
33,"[{""end"":5851,""text"":""Napoleon"",""start"":5843,""l...",upload/286914/4c31895c-Ferdinand_Foch_en.txt
34,"[{""end"":635,""text"":""Napoleon"",""start"":627,""lab...",upload/286914/462a208a-Félicité_de_La_Mennais_...
35,NaN,upload/286914/c2015b44-Donald_Adamson_en.txt
36,"[{""end"":2077,""text"":""Napoleon"",""start"":2069,""l...",upload/286914/a9db4682-Daniel_OConnell_en.txt
37,"[{""end"":61264,""text"":""Napoleon"",""start"":61256,...",upload/286914/4bfd5efe-Charles_de_Gaulle_en.txt
38,"[{""end"":7284,""text"":""Napoleon"",""start"":7276,""l...",upload/286914/1c78f39f-Auguste_Comte_en.txt
39,"[{""end"":1186,""text"":""Napoleon I"",""start"":1176,...",upload/286914/da313072-Archduke_Albrecht_Duke_...
40,"[{""end"":5257,""text"":""Napoleon"",""start"":5249,""l...",upload/286914/4d2c47fb-Antonio_Canova_en.txt
41,"[{""end"":877,""text"":""Napoleon I's"",""start"":865,...",upload/286914/e8a8c7ad-Antoine_Wiertz_en.txt
42,"[{""end"":1284,""text"":""Napoleon Bonaparte"",""star...",upload/286914/62df8ac9-Alexandre-Théodore_Bron...
43,"[{""end"":481,""text"":""Napoleon"",""start"":473,""lab...",upload/286914/4f346f15-Agostino_Barbarigo_en.txt
44,NaN,upload/286914/97023876-Achille_Baraguey_dHilli...
45,"[{""end"":894,""text"":""Napoleon I"",""start"":884,""l...",upload/286914/825d7ea3-Napoleon_III_en.txt

In [46]:
def extract_name(path):
    name = path.split('/')[-1]                  # 341b596e-Robert_Clive_en.txt
    name = re.sub(r'^[0-9a-f]+-', '', name)      # drop hash prefix -> Robert_Clive_en.txt
    name = re.sub(r'\.[^.]+$', '', name)         # drop extension -> Robert_Clive_en
    name = re.sub(r'_[a-z]{2}$', '', name)       # drop trailing language code -> Robert_Clive
    return name.replace('_', ' ')                # -> Robert Clive

ground_truth_napoleon['name'] = ground_truth_napoleon['text'].apply(extract_name)

In [47]:
ground_truth_napoleon

,label,text,name
0,"[{""end"":56226,""text"":""Napoleon"",""start"":56218,...",upload/286914/1fdf5af5-Voltaire_en.txt,Voltaire
1,"[{""end"":929,""text"":""Napoleon"",""start"":921,""lab...",upload/286914/5cc5cfef-Vincent-Marie_Viénot_Co...,Vincent-Marie Viénot Count of Vaublanc
2,"[{""end"":38625,""text"":""Napoleon Bonaparte"",""sta...",upload/286914/341b596e-Robert_Clive_en.txt,Robert Clive
3,NaN,upload/286914/6b10b085-Prince_Philippe_Count_o...,Prince Philippe Count of Paris
4,NaN,upload/286914/73f76387-Prince_Josias_of_Saxe-C...,Prince Josias of Saxe-Coburg-Saalfeld
5,"[{""end"":5885,""text"":""Napoleon's"",""start"":5875,...",upload/286914/d9f53915-Prince_Frederick_Duke_o...,Prince Frederick Duke of York and Albany
6,"[{""end"":9272,""text"":""Napoleon"",""start"":9264,""l...",upload/286914/3d352a8f-Prince_Ferdinand_Philip...,Prince Ferdinand Philippe Duke of Orléans
7,"[{""end"":6466,""text"":""Napoleon"",""start"":6458,""l...",upload/286914/f797fa95-Paolo_Virzì_en.txt,Paolo Virzì
8,"[{""end"":868,""text"":""Napoleon Bonaparte's"",""sta...",upload/286914/57a687d9-Oscar_I_of_Sweden_en.txt,Oscar I of Sweden
9,"[{""end"":627,""text"":""Napoleon"",""start"":619,""lab...",upload/286914/645a6703-Nicolas-Charles_Bochsa_...,Nicolas-Charles Bochsa
10,"[{""end"":3502,""text"":""Napoleon"",""start"":3494,""l...",upload/286914/3844b1cc-Mikhail_Tukhachevsky_en...,Mikhail Tukhachevsky
11,"[{""end"":5417,""text"":""Napoleon"",""start"":5409,""l...",upload/286914/e7bc14e5-Maurice_dElbée_en.txt,Maurice dElbée
12,"[{""end"":13052,""text"":""Napoleon"",""start"":13044,...",upload/286914/eb309a99-Leo_Tolstoy_en.txt,Leo Tolstoy
13,"[{""end"":63269,""text"":""Napoleon Bonaparte"",""sta...",upload/286914/c9546d53-Julius_Caesar_en.txt,Julius Caesar
14,"[{""end"":399,""text"":""Napoleon Bonaparte"",""start...",upload/286914/63c635bc-Józef_Bem_en.txt,Józef Bem
15,"[{""end"":2504,""text"":""Napoleon I"",""start"":2494,...",upload/286914/66553665-Joseph_Škoda_en.txt,Joseph Škoda
16,"[{""end"":25209,""text"":""Napoleon"",""start"":25201,...",upload/286914/adcd9a9f-Joseph_Haydn_en.txt,Joseph Haydn
17,"[{""end"":5050,""text"":""Napoleon"",""start"":5042,""l...",upload/286914/66040578-Joseph_de_Maistre_en.txt,Joseph de Maistre
18,"[{""end"":2552,""text"":""Napoleon I"",""start"":2542,...",upload/286914/2a7a0161-Joel_Roberts_Poinsett_e...,Joel Roberts Poinsett
19,"[{""end"":4537,""text"":""Napoleon"",""start"":4529,""l...",upload/286914/d70c6ed8-Joan_Elizabeth_Bichier_...,Joan Elizabeth Bichier des Âges
20,"[{""end"":286,""text"":""Napoleon"",""start"":278,""lab...",upload/286914/34c2e4aa-Jean-Antoine_Chaptal_en...,Jean-Antoine Chaptal
21,"[{""end"":228,""text"":""Napoleon's"",""start"":218,""l...",upload/286914/124940a6-Jean_Maximilien_Lamarqu...,Jean Maximilien Lamarque
22,"[{""end"":2050,""text"":""Napoleon's"",""start"":2040,...",upload/286914/88288647-Jacques_Laffitte_en.txt,Jacques Laffitte
23,"[{""end"":1873,""text"":""Napoleon"",""start"":1865,""l...",upload/286914/4e7f3b1c-Ida_Laura_Pfeiffer_en.txt,Ida Laura Pfeiffer
24,"[{""end"":368,""text"":""Napoleon"",""start"":360,""lab...",upload/286914/f33b29d3-Germinal_Pierre_Dandeli...,Germinal Pierre Dandelin
25,"[{""end"":1422,""text"":""Napoleon Bonaparte"",""star...",upload/286914/f31a453d-Georges_Cadoudal_en.txt,Georges Cadoudal
26,"[{""end"":13251,""text"":""Napoleon"",""start"":13243,...",upload/286914/1a0518d4-Gaspard_de_Prony_en.txt,Gaspard de Prony
27,"[{""end"":2135,""text"":""Napoleon"",""start"":2127,""l...",upload/286914/fcf3d393-Friedrich_Wilhelm_Freih...,Friedrich Wilhelm Freiherr von Bülow
28,"[{""end"":112828,""text"":""Napoleon"",""start"":11282...",upload/286914/747aed0b-Frederick_II_Holy_Roman...,Frederick II Holy Roman Emperor
29,"[{""end"":4488,""text"":""Napoleon"",""start"":4480,""l...",upload/286914/5173fad9-Frederick_Augustus_I_of...,Frederick Augustus I of Saxony
30,"[{""end"":6951,""text"":""Napoleon Bonaparte"",""star...",upload/286914/a1b960d4-Franz_Joseph_Gall_en.txt,Franz Joseph Gall
31,"[{""end"":356,""text"":""Napoleon"",""start"":348,""lab...",upload/286914/0efa6af0-François_Christophe_de_...,François Christophe de Kellermann
32,"[{""end"":641,""text"":""Napoleon"",""start"":633,""lab...",upload/286914/3ecee844-Francisco_Martínez_de_l...,Francisco Martínez de la Rosa
33,"[{""end"":5851,""text"":""Napoleon"",""start"":5843,""l...",upload/286914/4c31895c-Ferdinand_Foch_en.txt,Ferdinand Foch
34,"[{""end"":635,""text"":""Napoleon"",""start"":627,""lab...",upload/286914/462a208a-Félicité_de_La_Mennais_...,Félicité de La Mennais
35,NaN,upload/286914/c2015b44-Donald_Adamson_en.txt,Donald Adamson
36,"[{""end"":2077,""text"":""Napoleon"",""start"":2069,""l...",upload/286914/a9db4682-Daniel_OConnell_en.txt,Daniel OConnell
37,"[{""end"":61264,""text"":""Napoleon"",""start"":61256,...",upload/286914/4bfd5efe-Charles_de_Gaulle_en.txt,Charles de Gaulle
38,"[{""end"":7284,""text"":""Napoleon"",""start"":7276,""l...",upload/286914/1c78f39f-Auguste_Comte_en.txt,Auguste Comte
39,"[{""end"":1186,""text"":""Napoleon I"",""start"":1176,...",upload/286914/da313072-Archduke_Albrecht_Duke_...,Archduke Albrecht Duke of Teschen
40,"[{""end"":5257,""text"":""Napoleon"",""start"":5249,""l...",upload/286914/4d2c47fb-Antonio_Canova_en.txt,Antonio Canova
41,"[{""end"":877,""text"":""Napoleon I's"",""start"":865,...",upload/286914/e8a8c7ad-Antoine_Wiertz_en.txt,Antoine Wiertz
42,"[{""end"":1284,""text"":""Napoleon Bonaparte"",""star...",upload/286914/62df8ac9-Alexandre-Théodore_Bron...,Alexandre-Théodore Brongniart
43,"[{""end"":481,""text"":""Napoleon"",""start"":473,""lab...",upload/286914/4f346f15-Agostino_Barbarigo_en.txt,Agostino Barbarigo
44,NaN,upload/286914/97023876-Achille_Baraguey_dHilli...,Achille Baraguey dHilliers
45,"[{""end"":894,""text"":""Napoleon I"",""start"":884,""l...",upload/286914/825d7ea3-Napoleon_III_en.txt,Napoleon III

In [48]:
con = duckdb.connect('data/out/napo_sources.db')
title_to_id = con.execute("""
    SELECT 'Q' || wp.wikidata_id, wp.page_title
    FROM wiki_page wp
    JOIN extract e ON e.wiki_page_id = wp.wiki_page_id
""").fetchall()

con.close()

In [49]:
title_to_id

[('Q63023', 'Friedrich Wilhelm Freiherr von Bülow'),
 ('Q607190', 'Paolo Virzì'),
 ('Q451608', 'Gaspard de Prony'),
 ('Q334973', 'Félicité de La Mennais'),
 ('Q115995', "Achille Baraguey d'Hilliers"),
 ('Q360481', 'Vincent-Marie Viénot, Count of Vaublanc'),
 ('Q7243', 'Leo Tolstoy'),
 ('Q57511', 'Franz Joseph Gall'),
 ('Q78873', 'Ida Laura Pfeiffer'),
 ('Q7721', 'Napoleon III'),
 ('Q266339', 'Józef Bem'),
 ('Q310807', 'Archduke Albrecht, Duke of Teschen'),
 ('Q192615', 'Ferdinand Foch'),
 ('Q456812', 'Donald Adamson'),
 ('Q356933', 'François Christophe de Kellermann'),
 ('Q723247', "Maurice d'Elbée"),
 ('Q665957', 'Jacques Laffitte'),
 ('Q5547', 'Antonio Canova'),
 ('Q52926', 'Oscar I of Sweden'),
 ('Q162296', 'Robert Clive'),
 ('Q580516', 'Jean Maximilien Lamarque'),
 ('Q314917', "Daniel O'Connell"),
 ('Q555304', 'Georges Cadoudal'),
 ('Q142141', 'Mikhail Tukhachevsky'),
 ('Q354477', 'Prince Philippe, Count of Paris'),
 ('Q983354', 'Germinal Pierre Dandelin'),
 ('Q7349', 'Joseph Haydn'),
 ('Q130221', 'Frederick II, Holy Roman Emperor'),
 ('Q68771', 'Prince Josias of Saxe-Coburg-Saalfeld'),
 ('Q1048', 'Julius Caesar'),
 ('Q395582', 'Agostino Barbarigo'),
 ('Q251397', 'Nicolas-Charles Bochsa'),
 ('Q2042', 'Charles de Gaulle'),
 ('Q27357', 'Francisco Martínez de la Rosa'),
 ('Q723956', 'Joel Roberts Poinsett'),
 ('Q1342645', 'Alexandre-Théodore Brongniart'),
 ('Q9068', 'Voltaire'),
 ('Q53444', 'Frederick Augustus I of Saxony'),
 ('Q708011', 'Jean-Antoine Chaptal'),
 ('Q309854', 'Joseph de Maistre'),
 ('Q451365', 'Joan Elizabeth Bichier des Âges'),
 ('Q12718', 'Auguste Comte'),
 ('Q458688', 'Prince Ferdinand Philippe, Duke of Orléans'),
 ('Q79165', 'Joseph Škoda'),
 ('Q352978', 'Antoine Wiertz'),
 ('Q213573', 'Prince Frederick, Duke of York and Albany')]

In [50]:
# build a lookup dict from the tuple list (Qid, name) -> {name: Qid}
name_to_qid = {name: qid for qid, name in title_to_id}
name_to_qid = {k.replace(',', '').replace("'", ''): v for k, v in name_to_qid.items()}
ground_truth_napoleon['ID'] = ground_truth_napoleon['name'].map(name_to_qid)

In [51]:
ground_truth_napoleon['label'] = ground_truth_napoleon['label'].apply(
    lambda x: json.loads(x) if pd.notna(x) else x
)

In [52]:
def get_weight(x):
    if isinstance(x, list):
        return len(x)
    return 0

ground_truth_napoleon['GT_weight'] = ground_truth_napoleon['label'].apply(get_weight)

In [53]:
ground_truth_napoleon = ground_truth_napoleon.drop(['label', 'text'], axis=1)

In [54]:
ground_truth_napoleon

                                         name        ID  GT_weight
0                                    Voltaire     Q9068          1
1      Vincent-Marie Viénot Count of Vaublanc   Q360481         13
2                                Robert Clive   Q162296          2
3              Prince Philippe Count of Paris   Q354477          0
4       Prince Josias of Saxe-Coburg-Saalfeld    Q68771          0
5    Prince Frederick Duke of York and Albany   Q213573          1
6   Prince Ferdinand Philippe Duke of Orléans   Q458688          2
7                                 Paolo Virzì   Q607190          1
8                           Oscar I of Sweden    Q52926          3
9                      Nicolas-Charles Bochsa   Q251397          1
10                       Mikhail Tukhachevsky   Q142141          1
11                             Maurice dElbée   Q723247          1
12                                Leo Tolstoy     Q7243          2
13                              Julius Caesar     Q1048          2
14                                  Józef Bem   Q266339          2
15                               Joseph Škoda    Q79165          1
16                               Joseph Haydn     Q7349          1
17                          Joseph de Maistre   Q309854          2
18                      Joel Roberts Poinsett   Q723956          5
19            Joan Elizabeth Bichier des Âges   Q451365          1
20                       Jean-Antoine Chaptal   Q708011         18
21                   Jean Maximilien Lamarque   Q580516         12
22                           Jacques Laffitte   Q665957          4
23                         Ida Laura Pfeiffer    Q78873          1
24                   Germinal Pierre Dandelin   Q983354          1
25                           Georges Cadoudal   Q555304          2
26                           Gaspard de Prony   Q451608          1
27       Friedrich Wilhelm Freiherr von Bülow    Q63023          4
28            Frederick II Holy Roman Emperor   Q130221          3
29             Frederick Augustus I of Saxony    Q53444         19
30                          Franz Joseph Gall    Q57511          1
31          François Christophe de Kellermann   Q356933         11
32              Francisco Martínez de la Rosa    Q27357          1
33                             Ferdinand Foch   Q192615          4
34                     Félicité de La Mennais   Q334973          5
35                             Donald Adamson   Q456812          0
36                            Daniel OConnell   Q314917          3
37                          Charles de Gaulle     Q2042          4
38                              Auguste Comte    Q12718          1
39          Archduke Albrecht Duke of Teschen   Q310807          1
40                             Antonio Canova     Q5547         12
41                             Antoine Wiertz   Q352978          1
42              Alexandre-Théodore Brongniart  Q1342645          2
43                         Agostino Barbarigo   Q395582          1
44                 Achille Baraguey dHilliers   Q115995          0
45                               Napoleon III     Q7721         33

In [ ]:
ground_truth_napoleon.to_csv('../data/weight_files/GT_weights.csv', index=False)